# Basic Settings
title: Prompt engineering
description: Repository of Generative AI Prompting

# Author Information
author:
  name: Marcus Mister
  email: mmister411@gmail.com

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"

# Social Media
twitter_username: marcus.t.mister
github_username: mmister411

# Build Settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Theme
remote_theme: "tbakerx/react-resume-template"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
