# Basic Settings
title: Prompt engineering
description: Repository of Generative AI Prompting

# Author Information
author:
  name: Marcus Mister
  email: mmister411@gmail.com

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Argument Evaluation"
    url: "/llm/argumentevaluation"
  - title: "Balanced Exposition"
    url: "/llm/balanced_exposition"

# Social Media
twitter_username: marcus.t.mister
github_username: mmister411

# Build Settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Theme
remote_theme: pages-themes/slate@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one
